### ISSUE TITLE
Replace coreferences within the text

### ISSUE THREAD

**Issue by malik-majeed** [msg-systems/coreferee#1]
Is there any build-in option to replace / resolve the identified coreference within the text.

**Example in neuralcoref:**

`doc = nlp(u'Deepika has a dog. She loves him. The movie star has always been fond of animals')`

`doc._.coref_resolved`

**Output:**

'Deepika has a dog. Deepika loves a dog. Deepika has always been fond of animals'

**Comment by richardpaulhudson** [comment]
Not yet, although the resolve() function could be used to implement such a feature fairly easily:

>>>print(doc[7])
him
>>>print(doc._.coref_chains.resolve(doc[7]))
[dog]
>>>print(list(doc._.coref_chains.resolve(doc[7])[0].subtree))
[a, dog]

**Comment by ohmeow** [comment]
You can use this for replacements ...
```
updated_docs = []
for doc in nlp.pipe(docs):
    new_doc = []
    for token in doc:
        tok = doc._.coref_chains.resolve(token) or token
        tok_text = ' and '.join([t.text for t in tok]) if(isinstance(tok, list)) else tok.text
        tok_text += token.whitespace_
        new_doc.append(tok_text)

    updated_docs.append(''.join(new_doc))
```

**Comment by richardpaulhudson** [comment]
Many thanks @ohmeow - I am sure many people will find this code useful.

After a lot of consideration, I have decided not to implement a replacement feature within the library. The reason is that such a feature only works well for nouns and pronouns. These are the only parts of speech that are relevant for English, but German, Polish and many other languages for which Coreferee models might be generated in the future also mark anaphora on other parts of speech for which replacements would be much more complicated or even impossible.
