### ISSUE TITLE
Doesnt work with new trf model

### ISSUE THREAD

**Issue by AleksandrTulenkov** [msg-systems/coreferee#11]
Got: ModelNotSupportedError: en_core_web_trf version 3.1.0

**Comment by KTRosenberg** [comment]
Re: your comment on the Spacy thread. If this is in fact broken, I suppose I will be unable to use it.

**Comment by AleksandrTulenkov** [comment]
It works Ok as a native spacy model, for example with the NER task, but when I'm trying to add coref pipe I got the issue

**Comment by richardpaulhudson** [comment]
Hi everyone, I am currently working on adding support for Python 3.9 and spaCy 3.1 and the associated English and German models. I hope to release in the next couple of weeks. In the meantime, if you're feeling brave, you could also try downloading the development branch and installing it (`python3 -m pip install .` then `python3 -m coreferee install en`) from the downloaded root directory) which should now work.

**Comment by KTRosenberg** [comment]
Thanks. Out of curiosity, since in my case I am focusing on English accuracy as opposed to multilingual output, is it safer to stick with the old Spacy + neuralcoref? The multilingual support is great and I’d definitely use this in many cases, but I am concerned about stability and making sure the English results are good.

**Comment by richardpaulhudson** [comment]
I used Neuralcoref for several years before I decided to develop Coreferee mainly because I couldn't get Neuralcoref working with other languages. It's important to realize that Coreferee is aiming to find a somewhat more restricted range of coreference types than Neuralcoref is, largely because Coreferee was written for a particular purpose (see the README.md for more explanation). Although I haven't done a formal comparison, I would imagine the results are of broadly comparable quality for those coreference types that both libraries are aiming to capture.

One thing I would say is that Neuralcoref brings technical restrictions with it that you might find a pain: for example, I never found a way of serializing documents that contained Neuralcoref annotations. And I also wouldn't underestimate the difference in quality between the early versions of spaCy that Neuralcoref supports and modern versions: it is likely to be much more significant overall than the coreference library you are using.

**Comment by KTRosenberg** [comment]
That makes sense. I am trying to figure out how to turn the Coreferee results into a JSON to send over a network though, and the [index : []] format doesn't really conform to a Python or JS style object "shape." I wonder if there's some hidden to_json or serialization function that might make this easier(?)

**Comment by richardpaulhudson** [comment]
You could have a look at the serialization tests in https://github.com/msg-systems/coreferee/blob/master/tests/common/test_tech_common.py.

**Comment by KTRosenberg** [comment]
Thanks. Last question: would it be a viable solution to call resolve on every token, or is it slow to call on tokens even if there is no coreference on them? I ask because maybe it's simplest just to send things that way since I probably want to have one "true" identifier per entity.

**Comment by ansh-lehri** [comment]
> Got: ModelNotSupportedError: en_core_web_trf version 3.1.0

Hey @AleksandrTulenkov, have you figured out how to make the coreferee work for the en_core_web_trf = 3.1.0 model? I am having the same issue.

**Comment by AleksandrTulenkov** [comment]
> > Got: ModelNotSupportedError: en_core_web_trf version 3.1.0
> 
> Hey @AleksandrTulenkov, have you figured out how to make the coreferee work for the en_core_web_trf = 3.1.0 model? I am having the same issue.

For now, just using previos version :(

**Comment by richardpaulhudson** [comment]
I have just released version 1.1.0, which should have solved the problem.
