### ISSUE TITLE
illegal hardware instruction on macOS

### ISSUE THREAD

**Issue by fhamborg** [msg-systems/coreferee#23]
Hi, I followed the instructions from the readme, e.g., used a Py 3.9.5 environment, spacy = 3.1.2 and then installed coreferee. However, when running `python -m coreferee install en` I get

```
python -m coreferee install en
[1]    22471 illegal hardware instruction  python -m coreferee install en
```

Note that this error occurs also when executing `import spacy` but only *after* installing coreferee. Prior to the installation of coreferee, `import spacy` just works fine, so I suspect that the cause of this issue has to do with coreferee or perhaps one of its dependent libraries. For instance, I noticed that during coreferee's installation some libraries installed by spacy previously are replaced with older versions, see:

```
[...]
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.2
    Uninstalling typing-extensions-3.10.0.2:
      Successfully uninstalled typing-extensions-3.10.0.2
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.2
    Uninstalling numpy-1.21.2:
      Successfully uninstalled numpy-1.21.2
Successfully installed absl-py-0.14.1 astunparse-1.6.3 cachetools-4.2.4 coreferee-1.1.0 flatbuffers-1.12 gast-0.4.0 google-auth-2.3.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.34.1 h5py-3.1.0 keras-2.4.3 keras-nightly-2.5.0.dev2021032900 keras-preprocessing-1.1.2 markdown-3.3.4 numpy-1.19.5 oauthlib-3.1.1 opt-einsum-3.3.0 protobuf-3.18.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.0 rsa-4.7.2 scipy-1.7.1 six-1.15.0 tensorboard-2.7.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.5.1 tensorflow-estimator-2.5.0 termcolor-1.1.0 typing-extensions-3.7.4.3 werkzeug-2.0.2 wrapt-1.12.1
```

**Comment by richardpaulhudson** [comment]
So the problem is that tensorflow doesn't work out of the box on the M1 chipset. I have now got coreferee working on my M1 MacBook Pro (running MacOS v12.0.1) via the following steps:

1) Download and install the Miniforge3 conda environment as specified at https://developer.apple.com/metal/tensorflow-plugin/ (although I couldn't get things working using the rest of the instructions on the page).

2) Create and activate a new Conda environment, e.g.:

```
conda create --name coreferee
conda activate coreferee
```

3) Install the Tensorflow artefacts required to run on M1:

```
conda install -c apple tensorflow-deps
python3 -m pip install tensorflow-macos
python3 -m pip install tensorflow-metal
```

4) Install spaCy via conda: `conda install -c conda-forge spacy`

5) As the necessary changes to the Coreferee dependencies are not yet on the master branch, download and install the development branch: 

```
git clone --branch=development https://github.com/msg-systems/coreferee
cd coreferee
python3 -m pip install .
```

You should then be good to install the spaCy and coreferee models in the normal way.
