### ISSUE TITLE
Word lists from Wordnet 

### ISSUE THREAD

**Issue by Pantalaymon** [msg-systems/coreferee#29]
Hello,

So First of all, thank you for this project which is very well documented.
I am currently working on adding support for french using the DEMOCRAT corpus.

As I will need word lists, I see in the licence file that the lists in the data directories are derived from Wordnet. So I got my hands on [WOLF](http://pauillac.inria.fr/~sagot/index.html#wolf), a similar (derived from WordNet) lexical ressource for french.

So I was wondering if you could give more details on how to produce those .dat files. I am namely interested in the person_words.dat ,  exclusively_person_words.dat and animal_words.dat files (the criteria used to filter, which files of WordNet ...) . 
If possible, it would be great if you could share the code used to produce them.

**Comment by richardpaulhudson** [comment]
Hi @Pantalaymon, it would be great if you could add support for French! Unfortunately I no longer have the code I used to produce the .dat files, but I think that is because I used a combination of very simple code (2-3 lines) and manual editing. Essentially, I iterated through the hyponym tree of e.g. the 'person' term in Wordnet to get all words that can refer to people; those words in the hyponym tree that had no homographs elsewhere in Wordnet were 'exclusively person words'. 

I would be surprised if you needed exact counterparts of these files for French - I needed them for English because 'he' and 'she' can normally only refer to people and animals, which as far as I know from my very limited knowledge is not the case for French. The .dat files for German, which has grammatical gender like French, may well be a better starting point. The essential question is - are there situations in French where the semantics of the word rather than its grammatical gender determines which pronoun(s) can refer to it? If so, you will need .dat files to list the words in question.

**Comment by Pantalaymon** [comment]
Thanks for your answer. Well, then I think that wouldn't be too much work to do.

I plan to use these word lists to filter out the possibility of anaphoric pairs for the pronouns "en" and "y" which, under some conditions, can respectively only refer to mass nouns and locations.
Although, I think I might abandon this idea as the spacy models don't seem to be reliable enough to identify those conditions.
