### ISSUE TITLE
Adding support for trf models without NER

### ISSUE THREAD

**Issue by Pantalaymon** [msg-systems/coreferee#31]
Hello,

As I am approaching the end of my enterprise to add support for french, I notice that the performance of the coreference resolution is a lot hampered by the performance of the used spacy model as even the large model "`fr_core_news_lg`" is not optimal. 
However , the CamemBERT-based model "`fr_dep_news_trf`" yields a very noticeably better lemmatisation, tagging, morphological features and parsing. The downside is: it does not come with Named entity recognition in its pipeline.

I was wondering if it is possible to use the NER component of a smaller model, in the same way that the english coreferee model does with the word vectors. 
I see that this was not done for the german's (which is in a similar situation as french) `de_dep_news_trf`, so I figured there was maybe a reason I should not attempt to use this strategy for french?

If it is possible, how should I go about i?

**Comment by richardpaulhudson** [comment]
I'm glad to hear you've made so much progress 💯. What you are proposing sounds like a good idea and I can imagine it would lead to the best results, but it is probably a bit more work than what Coreferee currently does with the word vectors. This is because the word vectors are used at the level of individual tokens, whereas what you are suggesting would involve merging data at the document level.

You would need to parse each document with both models and the complicating factor is that you can't presume that a given word would necessary emerge with the same token index on both words. So you would need to scan through the two documents sequentially, comparing the `Token.text` values of each and ensuring that the named-entity data from the one document is assigned to the right tokens in the second document.

It might be worth looking at https://github.com/msg-systems/coreferee/blob/master/coreferee/training/loaders.py where I do something similar reading in non-spaCy training information and adding it to spaCy documents.

**Comment by Pantalaymon** [comment]
Thanks for your encouragements ! 
I see, this is indeed more complicated than I thought. I might try to do that in a later version if Explosion does not plan to release trf_core- models for languages other than english any time soon .

This might not be the best thread to ask but I have a little question regarding licences as I will probably issue a pull request soon:
- Should I leave as such the line` # Copyright 2021 msg systems ag` at the beginning of the files like language_specific_rules ?
