### ISSUE TITLE
retokenize can change the index values

### ISSUE THREAD

**Issue by lauvil** [msg-systems/coreferee#47]
I have a program where I need to call retokenize to combine specific tokens. This changes the indices of tokens and thus the coreferences are no longer pointing to the correct tokens. I have created a work around that adjusts these indices values, but I thought I'd let you know about this problem. I still have some issue where I clearly have not adjusted everything correctly because resolve is returning None instead of a value.

**Comment by richardpaulhudson** [comment]
I understand the problem, but I don't think that the right solution would be for Coreferee to react to the retokenization. This would get far too complex: if token 1 and 2 are merged and a coreference has been marked on token 2, does this coreference then apply to the new, merged token? And the same question would occur when tokens are split.

Instead, I think the solution is to retokenize and then call Coreferee. This involves calling it explicitly rather than adding it to the pipeline and is achieved using this code:

```
from coreferee.manager import CorefereeManager
annotator = CorefereeManager().get_annotator(nlp)
annotator.annotate(doc)
```
