### ISSUE TITLE
Resolved text

### ISSUE THREAD

**Issue by tteodoro** [msg-systems/coreferee#53]
Are there any plans for adding a "resolved_text"-type of attribute (i.e., the version of the doc/doc text with resolved spans?

**Comment by richardpaulhudson** [comment]
You can get the information you're looking for at the level of individual words with the `resolve()` method and it shouldn't be too difficult to use this to build a `resolved_text` for English. However, the library doesn't offer this as a standard feature because it wouldn't work for some other languages in the way it does for English.
