### ISSUE TITLE
Access to the score of the chain?

### ISSUE THREAD

**Issue by marmg** [msg-systems/coreferee#9]
Hi,

I've seen some cases in which the correference resolution fails, adding a wrong correference and missing the good one. So I wonder if there is any way to access to the score of the coreference resolution and if there are other options for the resolution that maybe are not being chosen as the correct ones by the network but they could be selected with rules.

Thanks.

PD: This is the case in which is failing:

... This seems to be the case for climate change. All of the available evidence shows that **it** is real, and **it** has consequences. ...

In this case, it relates the bold it(s) with All and not with climate change.

Best regards

**Comment by richardpaulhudson** [comment]
Coreferee is designed as an end-to-end solution that generates internally consistent chains, i.e. a chain may not end up containing two pronouns that cannot possibly agree with each other. It does not attempt to do this for alternative interpretations as this would quickly get unmanageably complicated.

Having said that, you can access alternative interpretations as long as you are happy to process pairs of words rather than chains. Check out the source code, then comment out the code block starting with `if not used_in_training` in `annotation.py`. You will find the token._.coref_chains objects now retain a lot of extra information including the scores for alternative interpretations.
